name: Sync Demo File to Destination Repo

on:
  push:
    branches:
      - main

jobs:
  sync-demo-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Clone Destination Repository
        run: |
          git clone https://krishnasugarinc:${{ secrets.PAT_TOKEN }}@github.com/krishnasugarinc/dump-krishna.git dump-krishna
          cd dump-krishna
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy Demo File
        run: |
          cp demo dump-krishna/demo

      - name: Commit and Push Changes
        run: |
          cd dump-krishna
          git add demo
          git commit -m "Sync demo file from krishna repo" || echo "No changes to commit"
          git push origin main || echo "Push failed"
