name: Sync Demo File to Destination Repo

on:
  push:
    branches:
      - main

jobs:
  sync-demo-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Clone Destination Repository
        run: |
          git clone https://<your-username>:${{ secrets.PAT_TOKEN }}@github.com/krishnasugarinc/dump-krishna.git destination_repo
          cd destination_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy Demo File
        run: |
          cp demo destination_repo/demo

      - name: Commit and Push Changes
        run: |
          cd destination_repo
          git add demo
          git commit -m "Sync demo file from krishna repo"
          git push origin main
