name: Sync All Files and Folders to Child Repos

on:
  push:
    branches:
      - main

jobs:
  sync-child-repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - dump-krishna

    steps:
      # Checkout the source repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      # Clone the destination repository
      - name: Clone Destination Repository
        run: |
          git clone https://krishnasugarinc:${{ secrets.PAT_TOKEN }}@github.com/krishnasugarinc/${{ matrix.repo }}.git
          cd ${{ matrix.repo }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Sync all files and folders from the source repository to the destination repository
      - name: Sync Files and Folders
        run: |
          rsync -av --exclude '.git' --exclude '.github' ./ ${{ matrix.repo }}/

      # Commit and push changes to the destination repository
      - name: Commit and Push Changes
        run: |
          cd ${{ matrix.repo }}
          git add .
          git commit -m "Sync all files and folders from krishna repo"
          git push origin main
