name: Sync Specific Files to Destination Repo

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      # Step 2: Clone the Destination Repository
      - name: Clone Destination Repository
        run: |
          git clone https://<your-username>:${{ secrets.DEST_REPO_TOKEN }}@github.com/<destination-owner>/<destination-repo>.git destination_repo
          cd destination_repo
          git config user.name "<your-username>"
          git config user.email "<your-email>"

      # Step 3: Copy Specific Files
      - name: Copy Specific Files
        run: |
          cp path/to/file1 destination_repo/path/to/file1
          cp path/to/file2 destination_repo/path/to/file2

      # Step 4: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          cd destination_repo
          git add .
          git commit -m "Sync specific files from source repository"
          git push origin main
