name: Sync Demo File to Child Repos

on:
  push:
    branches:
      - main

jobs:
  sync-child-repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - dump-krishna

    steps:
      # Checkout the source repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      # Clone the destination repository (matrix handles both child repos)
      - name: Clone Destination Repository
        run: |
          git clone https://krishnasugarinc:${{ secrets.PAT_TOKEN }}@github.com/krishnasugarinc/${{ matrix.repo }}.git
          cd ${{ matrix.repo }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Copy files to the destination repository
      - name: Copy Files
        run: |
          cp demo ${{ matrix.repo }}/new
          cp krishna-demo ${{ matrix.repo }}/krishna-demo

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          cd ${{ matrix.repo }}
          git add new krishna-demo
          git commit -m "Sync demo and krishna-demo files from krishna repo"
          git push origin main
